"""empty message

Revision ID: 06069f51ef95
Revises: 58e5ac8b9773
Create Date: 2022-07-24 16:05:34.608087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06069f51ef95'
down_revision = '58e5ac8b9773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Artist', ['name'])
    op.create_unique_constraint(None, 'Artist', ['website'])
    op.create_unique_constraint(None, 'Artist', ['phone'])
    op.create_unique_constraint(None, 'Venue', ['name'])
    op.create_unique_constraint(None, 'Venue', ['phone'])
    op.create_unique_constraint(None, 'Venue', ['website'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    # ### end Alembic commands ###
